###################################
# author: chatgpt
# co-author: ashraf minhaj
# email: ashraf_minhaj@yahoo.com
# 
# date: 16-11-23
# run the container for 1 hour
###################################

# Use a lightweight base image
FROM debian

# Run a command that will keep the container running for some time
CMD ["sh", "-c", "while true; do sleep 3600; done"]