#########################################
# author: ashraf minhaj
# email : ashraf_minhaj@yahoo.com
# 
# date: 16-11-23
# run my_app and monitor if it crashes
#########################################

version: '3'

name: my_failing_app

services:
  my_app:
    container_name: failing_app
    build:
      context: .
      dockerfile: Dockerfile

  pydonitor:
    tty: true
    container_name: pydonitor
    image: ashraftheminhaj/pydonitor:1.1
    environment:
      - container_name=failing_app
      - discord_webhook_url=https://custom/webhook
    depends_on:
      - my_app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/